Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Настройка сети
  config.vm.network "private_network", ip: "192.168.56.10"

  # ГОВОРИМ VAGRANT ИСПОЛЬЗОВАТЬ СТАТИЧЕСКИЙ IP ДЛЯ SSH
  config.ssh.host = "192.168.56.10"
  config.ssh.port = 22
  # Это важно: не даем Vagrant заменять ключи, чтобы не запутаться
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    vb.memory = "1024"
    vb.cpus = 1
    vb.gui = true # Оставь включенным, чтобы видеть, что ВМ загрузилась до логина
  end
end