Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Фиксированный IP, чтобы Ansible всегда знал, куда идти
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Важно: не генерировать новый ключ, чтобы путь был предсказуем
  #config.ssh.insert_key = false
end